# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "resend-rs"
version = "0.7.0"
edition = "2021"

license = "MIT"
readme = "./README.md"

authors = ["Antonios Barotsis <antonios.barotsis@proton.me>"]
repository = "https://github.com/resend/resend-rust"
homepage = "https://resend.com/docs/send-with-rust"
documentation = "https://docs.rs/resend-rs"

categories = ["email", "web-programming"]
keywords = ["email", "resend"]
description = "A minimal Resend client."

[features]
default = ["native-tls"]

blocking = ["reqwest/blocking", "maybe-async/is_sync"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
reqwest = { version = "0.12.4", default-features = false, features = ["json"] }
serde = { version = "1.0.199", features = ["derive"] }
ecow = { version = "0.2.2", features = ["serde"] }
thiserror = { version = "1.0.59" }
maybe-async = { version = "0.2.10" }
governor = "0.6.3"
rand = "0.8.5"

[dev-dependencies]
tokio = { version = "1.37.0", features = ["macros", "test-util", "rt-multi-thread"] }
